config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: "pages#home"

  get "/scan", to: "pages#scan", as: :scan

  resources :foods, only: ['index', 'show', 'new', "create", "update", "edit"] do
    resources :favorites, only: ['create']
  end
  resources :favorites, only: ['destroy']
  
  # resources :users, only: ['edit', 'update']

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many_attached :photos

  # validates :ingredient_list, presence: true
  # validates :photos, presence: true
  # after_save :extract_ingredients, :translate

  def extract_ingredients
    require "./app/services/Ocr.rb"
    extracted_text = Ocr.extract_text(self.photos[0])
    formatted_text = extracted_text
    self.ingredient_list = formatted_text
    save
  end

  def translate
    require "./app/services/Translator.rb"

    translated_ingredient_list = DeepTranslator.translate_ingredients(self.ingredient_list)
    self.ingredient_list = translated_ingredient_list
    save
  end

  def update_flag(preference, flag)
    if preference == "vegan"
      self.vegan = flag
      self.save
    elsif preference == "vegetarian"
      self.vegetarian = flag
      self.save
    elsif preference == "pescetarian"
      self.pescetarian = flag
      self.save
    elsif preference == "dairy-free"
      self.dairy_free = flag
      self.save
    else
      self.peanut_free = flag
      self.save
    end
  end

  def check(preference)
    if preference == "vegan"
      return self.vegan
    elsif preference == "vegetarian"
      return self.vegetarian
    elsif preference == "pescetarian"
      return self.pescetarian
    elsif preference == "dairy-free"
      return self.dairy_free
    else
      return self.peanut_free
    end
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  require 'json'
  require "open-uri"
  require "i18n"

  def index
    @foods = current_user.foods.reverse_order
  end

  def show
    @food = Food.find(params[:id])
    @ingredient_list = @food.ingredient_list.split(", ")
    @pref_arr = current_user.preferences.split(" ")
    @pref_flags
    pref_flags
    @ingredients
    @unknown_ingredients
    @false_ingredients
    @maybe_ingredients
    @true_ingredients
    get_ingredients
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      @food.extract_ingredients
      @ingredient_list = @food.ingredient_list.split(", ")
      classify_ingredients_individually
      classify_categories
      redirect_to food_path(@food)
    else
      flash[:error] = @food.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @food = Food.find(params[:id])
    if @food.photos.attach(food_params[:photos]) || food_params[:name].present?
      @food.name = food_params[:name] if food_params[:name].present?
      @food.save
      redirect_to food_path(@food)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :ingredient_list, :vegetarian, :pescetarian, :dairy_free, :peanut_free, :vegan, photos: [])
  end

  def get_ingredients
    @ingredients = []
    @unknown_ingredients = []
    @false_ingredients = []
    @maybe_ingredients = []
    @true_ingredients = []
    @ingredient_list.each do |ingredient|
      ing = Ingredient.find_by(name: ingredient.strip)
      if !ing.nil?
        @ingredients << ing
      else
        @unknown_ingredients << ingredient
      end
    end
    @ingredients.each do |ingredient|
      if (ingredient.full_check(@pref_arr).include?("false"))
        @false_ingredients << ingredient
      elsif (ingredient.full_check(@pref_arr).include?("can-be") && !@false_ingredients.include?(ingredient))
        @maybe_ingredients << ingredient
      else
        @true_ingredients << ingredient
      end
    end
    unless @unknown_ingredients.empty?
      @unknown_ingredients.each_with_index do |ingredient, index|
        translation = DeepL.translate ingredient, "JA", "EN"
        translation = translation.text
        description = Gpt.describe_unknown_ingredient(translation)
        @unknown_ingredients[index] = [ingredient, translation, description]
      end
    end
  end

  def classify_ingredients_individually
    # true, false, can-be, empty
    @preferences = [[], [], [], []]
    @ingredients = []
    @unknown_ingredients = []
    Gpt::ALL_PREFERENCES.each do |preference|
      @ingredient_list.each do |ingredient|
        ing = Ingredient.find_by(name: ingredient.strip)
        if !ing.nil?
          @ingredients << ing
          if ing.check(preference) == "true"
            @preferences[0] << ing
          elsif ing.check(preference) == "false"
            @preferences[1] << ing
          else
            @preferences[2] << ing
          end
        else
          @preferences[3] << ingredient
          @unknown_ingredients << ingredient
        end
      end
    end
    @preferences[0].uniq!
    @preferences[1].uniq!
    @preferences[2].uniq!
    @preferences[3].uniq!
    @ingredients.uniq!
    @unknown_ingredients.uniq!
  end

  def classify_categories
    Gpt::ALL_PREFERENCES.each do |preference|
      if (!@preferences[1].nil?)
        @preferences[1].each do |ingredient|
          if (ingredient.check(preference) == "false")
            @food.update_flag(preference, "false")
          end
        end
      end
      if (!@preferences[2].nil? && @food.check(preference).nil?)
        @preferences[2].each do |ingredient|
          if (ingredient.check(preference) == "can-be")
            @food.update_flag(preference, "can-be")
          end
        end
      end
      if (@food.check(preference).nil?)
        @food.update_flag(preference, "true")
      end
    end
  end

  def pref_flags
    @pref_flags = []
    @pref_arr.each do |pref|
      @pref_flags << @food.check(pref)
    end
  end
end

app/views/foods/_favorites_carousel.html.erb
<div class="cards-container" id="image-track">
  <% foods = foods.order(:created_at).reverse %>
  <% prefs = current_user.preferences.split(" ") %>
  <% foods.each do |food| %>
    <% checks = [] %>
    <% prefs.each do |pref| %>
      <% checks << food.check(pref) %>
    <% end %>
    <%= link_to food_path(food), class: "text-decoration-none food-card-container index-cards" do %>
      <% if checks.include?("false") %>
        <div class="red-border-card">
          <div class="false-food-history-item thumbnail">
            <%= cl_image_tag food.photos.last.key, height: 500, width: 300, crop: :fit, class:'bottom-border-green' %>
          </div>
          <div class="infos-index">
            <h3 class="food-title"><%= !food.name.nil? ? food.name : "Item ##{food.id}" %></h3>
            <div class="index-icons">
              <% prefs.each do |pref| %>
                <% check = food.check(pref) %>
                <%= image_tag("food_icons/#{"maybe-" if check == "can-be"}#{"not-" if check == "false"}#{pref}.png", class: "small-icon") %>
              <% end %>
            </div>
          </div>
            <% if favorites.find_by(food_id: food.id) %>
              <%= link_to favorite_path(favorites.where("food_id=#{food.id}").ids), data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-heart liked-heart" style="color: #ff0000;"></i>
              <% end %>
            <% else %>
              <%= link_to food_favorites_path(food), data: { turbo_method: :post } do %>
                <i class="fa-regular fa-heart unliked-heart"></i>
              <% end %>
            <% end %>
        </div>
      <% elsif checks.include?("can-be") %>
        <div class="yellow-border-card">
          <div class="can-be-food-history-item thumbnail">
            <%= cl_image_tag food.photos.last.key, height: 500, width: 300, crop: :fit, class:'bottom-border-green' %>
          </div>
          <div class="infos-index">
            <h3 class="food-title"><%= !food.name.nil? ? food.name : "Item ##{food.id}" %></h3>
            <div class="index-icons">
              <% prefs.each do |pref| %>
                <% check = food.check(pref) %>
                <%= image_tag("food_icons/#{"maybe-" if check == "can-be"}#{"not" if check == "false"}#{pref}.png", class: "small-icon") %>
              <% end %>
            </div>
          </div>
            <% if favorites.find_by(food_id: food.id) %>
              <%= link_to favorite_path(favorites.where("food_id=#{food.id}").ids), data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-heart liked-heart" style="color: #ff0000;"></i>
              <% end %>
            <% else %>
              <%= link_to food_favorites_path(food), data: { turbo_method: :post } do %>
                <i class="fa-regular fa-heart unliked-heart"></i>
              <% end %>
            <% end %>
        </div>
      <% else %>
        <div class="green-border-card">
          <div class="true-food-history-item thumbnail">
            <%= cl_image_tag food.photos.last.key, height: 500, width: 300, crop: :fit, class:'bottom-border-green' %>
          </div>
          <div class="infos-index">
            <h3 class="food-title"><%= !food.name.nil? ? food.name : "Item ##{food.id}" %></h3>
            <div class="index-icons">
              <% prefs.each do |pref| %>
                <% check = food.check(pref) %>
                <%= image_tag("food_icons/#{"maybe-" if check == "can-be"}#{"not" if check == "false"}#{pref}.png", class: "small-icon") %>
              <% end %>
            </div>
          </div>
            <% if favorites.find_by(food_id: food.id) %>
              <%= link_to favorite_path(favorites.where("food_id=#{food.id}").ids), data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-heart liked-heart" style="color: #ff0000;"></i>
              <% end %>
            <% else %>
              <%= link_to food_favorites_path(food), data: { turbo_method: :post } do %>
                <i class="fa-regular fa-heart unliked-heart"></i>
              <% end %>
            <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/foods/_food_carousel.html.erb
<div class="cards-container" id="image-track">
  <% foods = foods.order(:created_at).reverse %>
  <% prefs = current_user.preferences.split(" ") %>
  <% foods.each do |food| %>
    <% checks = [] %>
    <% prefs.each do |pref| %>
      <% checks << food.check(pref) %>
    <% end %>
    <%= link_to food_path(food), class: "text-decoration-none food-card-container index-cards" do %>
      <% if checks.include?("false") %>
        <div class="red-border-card">
          <div class="false-food-history-item thumbnail">
            <%= cl_image_tag food.photos.last.key, height: 500, width: 300, crop: :fit, class:'bottom-border-green' %>
          </div>
          <div class="infos-index">
            <h3 class="food-title"><%= !food.name.nil? ? food.name : "Item ##{food.id}" %></h3>
            <div class="index-icons">
              <% prefs.each do |pref| %>
                <% check = food.check(pref) %>
                <%= image_tag("food_icons/#{"maybe-" if check == "can-be"}#{"not-" if check == "false"}#{pref}.png", class: "small-icon") %>
              <% end %>
            </div>
          </div>
            <% if favorites.find_by(food_id: food.id) %>
              <%= link_to favorite_path(favorites.where("food_id=#{food.id}").ids), data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-heart liked-heart" style="color: #ff0000;"></i>
              <% end %>
            <% else %>
              <%= link_to food_favorites_path(food), data: { turbo_method: :post } do %>
                <i class="fa-regular fa-heart unliked-heart"></i>
              <% end %>
            <% end %>
        </div>
      <% elsif checks.include?("can-be") %>
        <div class="yellow-border-card">
          <div class="can-be-food-history-item thumbnail">
            <%= cl_image_tag food.photos.last.key, height: 500, width: 300, crop: :fit, class:'bottom-border-green' %>
          </div>
          <div class="infos-index">
            <h3 class="food-title"><%= !food.name.nil? ? food.name : "Item ##{food.id}" %></h3>
            <div class="index-icons">
              <% prefs.each do |pref| %>
                <% check = food.check(pref) %>
                <%= image_tag("food_icons/#{"maybe-" if check == "can-be"}#{"not" if check == "false"}#{pref}.png", class: "small-icon") %>
              <% end %>
            </div>
          </div>
            <% if favorites.find_by(food_id: food.id) %>
              <%= link_to favorite_path(favorites.where("food_id=#{food.id}").ids), data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-heart liked-heart" style="color: #ff0000;"></i>
              <% end %>
            <% else %>
              <%= link_to food_favorites_path(food), data: { turbo_method: :post } do %>
                <i class="fa-regular fa-heart unliked-heart"></i>
              <% end %>
            <% end %>
        </div>
      <% else %>
        <div class="green-border-card">
          <div class="true-food-history-item thumbnail">
            <%= cl_image_tag food.photos.last.key, height: 500, width: 300, crop: :fit, class:'bottom-border-green' %>
          </div>
          <div class="infos-index">
            <h3 class="food-title"><%= !food.name.nil? ? food.name : "Item ##{food.id}" %></h3>
            <div class="index-icons">
              <% prefs.each do |pref| %>
                <% check = food.check(pref) %>
                <%= image_tag("food_icons/#{"maybe-" if check == "can-be"}#{"not" if check == "false"}#{pref}.png", class: "small-icon") %>
              <% end %>
            </div>
          </div>
            <% if favorites.find_by(food_id: food.id) %>
              <%= link_to favorite_path(favorites.where("food_id=#{food.id}").ids), data: { turbo_method: :delete } do %>
                <i class="fa-solid fa-heart liked-heart" style="color: #ff0000;"></i>
              <% end %>
            <% else %>
              <%= link_to food_favorites_path(food), data: { turbo_method: :post } do %>
                <i class="fa-regular fa-heart unliked-heart"></i>
              <% end %>
            <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/foods/_history_vegan_history_item.html.erb
<div class="vegan-food-history-item">
  <%= link_to food_path(food), class: "text-decoration-none food-card-container" do %>
    <% if favorites.find_by(food_id: food.id) %>
      <%= link_to favorite_path(favorites.where("food_id=#{food.id}").ids), data: { turbo_method: :delete } do %>
        <i class="fa-solid fa-heart" style="color: #ff0000;"></i>
      <% end %>
    <% else %>
      <%= link_to food_favorites_path(food), data: { turbo_method: :post } do %>
        <i class="fa-regular fa-heart"></i>
      <% end %>
    <% end %>
    <%= cl_image_tag food.photos.last.key, height: 500, width: 300, crop: :fill, class:'border-green' %>
    <div class="vegan-item">
      <p>
        <i class="fa-solid fa-seedling" style="color: #ffffff;"></i>
        <%= food.name.present? ? food.name : "Item Nr.#{food.id}" %>
      </p>
    </div>
  <% end %>
</div>

app/views/foods/index.html.erb
<div class="index-container" data-controller="fav-his-toggler">
  <div class="bar-container">
    <div class="bar-item active" id="history-tab">History</div>
    <div class="bar-item" id="favorites-tab">Favorites</div>
  </div>
  <div class="content-container">
    <div class="tab-content" id="history-content">
      <%= render 'food_carousel', foods: current_user.foods, favorites: current_user.favorites %>
    </div>
    <div class="tab-content hidden" id="favorites-content">
      <%= render 'favorites_carousel', foods: current_user.fav_foods, favorites: current_user.favorites %>
    </div>
  </div>
</div>

app/views/foods/show.html.erb
<% if @pref_flags.include?("false") %>
  <div class="show-result-container d-flex flex-column red-border-image">
    <h1>You cannot eat this!</h1>
    <div class="d-flex flex-row">
      <% Gpt::ALL_PREFERENCES.each do |preference| %>
        <% if (@food.check(preference.gsub(/(and\s?)/,"")) == "false") %>
          <%= image_tag("food_icons/not-#{preference.gsub(/(and\s?)/,"")}.png", class: "medium-icon") %>
        <% elsif (@food.check(preference.gsub(/(and\s?)/,"")) == "can-be")   %>
          <%= image_tag("food_icons/maybe-#{preference.gsub(/(and\s?)/,"")}.png", class: "medium-icon") %>
        <% else %>
          <%= image_tag("food_icons/#{preference.gsub(/(and\s?)/,"")}.png", class: "medium-icon") %>
        <% end %>
      <% end %>
    </div>
  </div>
<% elsif (@pref_flags.include?("can-be") || @unknown_ingredients.count > 0) %>
  <div class="show-result-container d-flex flex-column yellow-border-image">
    <h1>Maybe you can eat this!</h1>
    <div class="d-flex flex-row">
      <% Gpt::ALL_PREFERENCES.each do |preference| %>
        <% if (@food.check(preference.gsub(/(and\s?)/,"")) == "false") %>
          <%= image_tag("food_icons/not-#{preference}.png", class: "medium-icon") %>
        <% elsif (@food.check(preference.gsub(/(and\s?)/,"")) == "can-be")   %>
          <%= image_tag("food_icons/maybe-#{preference.gsub(/(and\s?)/,"")}.png", class: "medium-icon") %>
        <% else %>
          <%= image_tag("food_icons/#{preference.gsub(/(and\s?)/,"")}.png", class: "medium-icon") %>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="show-result-container d-flex flex-column green-border-image">
    <h1>You can eat this!</h1>
    <div class="d-flex flex-row">
      <% Gpt::ALL_PREFERENCES.each do |preference| %>
        <% if (@food.check(preference.gsub(/(and\s?)/,"")) == "false") %>
          <%= image_tag("food_icons/not-#{preference.gsub(/(and\s?)/,"")}.png", class: "medium-icon") %>
        <% elsif (@food.check(preference.gsub(/(and\s?)/,"")) == "can-be")   %>
          <%= image_tag("food_icons/maybe-#{preference.gsub(/(and\s?)/,"")}.png", class: "medium-icon") %>
        <% else %>
          <%= image_tag("food_icons/#{preference.gsub(/(and\s?)/,"")}.png", class: "medium-icon") %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
<% unless @false_ingredients.length == 0 %>
  <div class="bar-container ingredient-show-container false-background">
    <h2>Not Safe</h2>
    <% @false_ingredients.each do |ingredient| %>
      <div class="wide-bar-card" data-controller="extended-infos" data-extended-infos-target="shover">
        <div class="toggle-grid" data-extended-infos-target="shrinker">
          <p class="text-wrap d-none" data-extended-infos-target="showup"><strong><%= ingredient.english_name.capitalize %></strong></p>
          <% if ingredient.english_name.length > 9 %>
            <p class="text-wrap" data-extended-infos-target="hider"><strong><%= ingredient.english_name.capitalize[0..8] %>...</strong></p>
          <% else %>
            <p class="text-wrap" data-extended-infos-target="hider"><strong><%= ingredient.english_name.capitalize %></strong></p>
          <% end %>
          <button class="btn toggler"  data-action="click->extended-infos#revealInfos">&gt;</button>
        </div>
        <div class="ingredient-preference-results">
          <% @pref_arr.each do |preference| %>
            <% if (ingredient.check(preference) == "false") %>
              <%= image_tag("food_icons/not-#{preference}.png", class: "small-icon") %>
            <% end %>
          <% end %>
        </div>
        <div class="d-none extended-infos" data-extended-infos-target="info">
          <p><strong>Description: </strong><%= ingredient.english_description %></p>
          <div class="extended-infos-grid">
            <%= link_to "Google it!", "http://www.google.com/search?q=#{ingredient.english_name}", target: '_blank', class: "btn btn-primary" %>
            <%= link_to "Report", "", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<% unless @maybe_ingredients.length == 0 %>
  <div class="bar-container ingredient-show-container maybe-background">
    <h2>Caution</h2>
    <% @maybe_ingredients.each do |ingredient| %>
      <div class="wide-bar-card" data-controller="extended-infos" data-extended-infos-target="shover">
        <div class="toggle-grid" data-extended-infos-target="shrinker">
          <p class="text-wrap d-none" data-extended-infos-target="showup"><strong><%= ingredient.english_name.capitalize %></strong></p>
          <% if ingredient.english_name.length > 9 %>
            <p class="text-wrap" data-extended-infos-target="hider"><strong><%= ingredient.english_name.capitalize[0..8] %>...</strong></p>
          <% else %>
            <p class="text-wrap" data-extended-infos-target="hider"><strong><%= ingredient.english_name.capitalize %></strong></p>
          <% end %>
          <button class="btn toggler"  data-action="click->extended-infos#revealInfos">&gt;</button>
        </div>
        <div class="ingredient-preference-results">
          <% @pref_arr.each do |preference| %>
            <% if (ingredient.check(preference) == "can-be") %>
              <%= image_tag("food_icons/maybe-#{preference}.png", class: "small-icon") %>
            <% end %>
          <% end %>
        </div>
        <div class="d-none extended-infos" data-extended-infos-target="info">
          <p><strong>Description: </strong><%= ingredient.english_description %></p>
          <div class="extended-infos-grid">
            <%= link_to "Google it!", "http://www.google.com/search?q=#{ingredient.english_name}", target: '_blank', class: "btn btn-primary" %>
            <%= link_to "Report", "", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<% unless @unknown_ingredients.length == 0 %>
  <div class="bar-container ingredient-show-container unknown-background">
    <h2>Unknown</h2>
    <% @unknown_ingredients.each do |ingredient| %>
      <div class="wide-bar-card gray-background" data-controller="extended-infos" data-extended-infos-target="shover">
        <div class="toggle-grid" data-extended-infos-target="shrinker">
          <p class="text-wrap d-none" data-extended-infos-target="showup"><strong><%= ingredient[1].capitalize %></strong></p>
          <% if ingredient[1].length > 9 %>
            <p class="text-wrap" data-extended-infos-target="hider"><strong><%= [ingredient[1]][0..8] %>...</strong></p>
          <% else %>
            <p class="text-wrap" data-extended-infos-target="hider"><strong><%= ingredient[1].capitalize %></strong></p>
          <% end %>
          <button class="btn toggler"  data-action="click->extended-infos#revealInfos">&gt;</button>
        </div>
        <div class="d-none extended-infos" data-extended-infos-target="info">
          <p>Sorry, we couldn't find <%= ingredient[0] %></p>
          <p><strong>Here is what we think it is:</strong> <%= ingredient[2] %></p>
          <div class="extended-infos-grid">
            <%= link_to "Google it!", "http://www.google.com/search?q=#{ingredient[0]}", target: '_blank', class: "btn btn-primary" %>
            <%= link_to "Report", "", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<% unless @true_ingredients.length == 0 %>
  <div class="bar-container ingredient-show-container true-background">
    <h2>Safe</h2>
    <% @true_ingredients.each do |ingredient| %>
      <div class="wide-bar-card" data-controller="extended-infos" data-extended-infos-target="shover">
        <div class="toggle-grid" data-extended-infos-target="shrinker">
          <p class="text-wrap d-none" data-extended-infos-target="showup"><strong><%= ingredient.english_name.capitalize %></strong></p>
          <% if ingredient.english_name.length > 9 %>
            <p class="text-wrap" data-extended-infos-target="hider"><strong><%= ingredient.english_name.capitalize[0..8] %>...</strong></p>
          <% else %>
            <p class="text-wrap" data-extended-infos-target="hider"><strong><%= ingredient.english_name.capitalize %></strong></p>
          <% end %>
          <button class="btn toggler"  data-action="click->extended-infos#revealInfos">&gt;</button>
        </div>
        <div class="ingredient-preference-results">
          <% @pref_arr.each do |preference| %>
            <% if (ingredient.check(preference) == "true") %>
              <%= image_tag("food_icons/#{preference}.png", class: "small-icon") %>
            <% end %>
          <% end %>
        </div>
        <div class="d-none extended-infos" data-extended-infos-target="info">
          <p><strong>Description: </strong><%= ingredient.english_description %></p>
          <div class="extended-infos-grid">
            <%= link_to "Google it!", "http://www.google.com/search?q=#{ingredient.english_name}", target: '_blank', class: "btn btn-primary" %>
            <%= link_to "Report", "", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<div class="pictures-container" data-controller="phototoggler">
  <% if @food.photos[1].present? %>
    <% if @pref_flags.include?("false") %>
      <%= cl_image_tag @food.photos[1].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "front", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image red-border-image" %>
      <%= cl_image_tag @food.photos[0].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "back", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image red-border-image d-none" %>
    <% elsif @pref_flags.include?("can-be") %>
      <%= cl_image_tag @food.photos[1].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "front", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image yellow-border-image" %>
      <%= cl_image_tag @food.photos[0].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "back", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image yellow-border-image d-none" %>
    <% else %>
      <%= cl_image_tag @food.photos[1].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "front", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image green-border-image" %>
      <%= cl_image_tag @food.photos[0].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "back", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image green-border-image d-none" %>
    <% end %>
  <% else %>
    <%= simple_form_for @food, method: "patch", data: { controller: "autosubmit", 'autosubmit-target': "form"} do |f| %>
      <div class="plus-icon-invisible">
        <div>
          <%= image_tag "icon_plus.png" %> Add Front Photo
        </div>
      </div>
      <%= f.input :photos, as: :file, label: false, input_html: { multiple: true, data: {action: "input->autosubmit#submitPicture"}, class: "invisible-form-small" } %>
    <% end %>
    <% if @pref_flags.include?("false") %>
      <%= cl_image_tag @food.photos[0].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "back", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image red-border-image" %>
    <% elsif @pref_flags.include?("can-be") %>
      <%= cl_image_tag @food.photos[0].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "back", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image yellow-border-image" %>
    <% else %>
      <%= cl_image_tag @food.photos[0].key, height: 300, width: 400, crop: :fill, data: {"phototoggler-target": "back", action: "click->phototoggler#togglePhoto"}, class: "big-centered-image green-border-image" %>
    <% end %>
  <% end %>
</div>
<div id="food-name-container">
  <% if @food.name.present? %>
    <h1 id="food-display-name"><%= @food.name %></h1>
  <% else %>
    <div class="name-submit-form-container">
      <%= simple_form_for @food, method: "patch", html: { id: "name-submit-form" } do |f| %>
        <%= f.input :name, label: false, placeholder: "Enter Product Name", class: 'food-name-input-field' %>
        <%= f.submit "+", class: "btn name-submit-btn" %>
      <% end %>
    </div>
  <% end %>
</div>